version: '3.8'

services:
  netdisk-search:
    build: .
    container_name: netdisk-search
    ports:
      - "3000:80"
    environment:
      - API_DOMAIN=https://x.x.x.x:8888
    restart: unless-stopped
